# Generated by Django 4.2.4 on 2024-03-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
